#pragma once

#include "Framework/import.h"
#include "Base/import.h"


#if (PLATFORM_TARGET == EPT_WINDOWS)
#include <windows.h>
#endif

namespace sys
{
	// 按钮状态
	enum class ButtonStatus
	{
		NONE = -1,
		// 按下按钮
		BUTTON_DOWN,
		// 放开按钮
		BUTTON_UP,
	};

	// 滚轮事件
	enum class ScrollEvent
	{
		// 向上滑动滚轮
		SCORLL_UP,
		// 向下滑动滚轮
		SCORLL_DOWN,
	};

	// 鼠标键
	enum class MouseKey
	{
		NONE = -1,
		// 左按钮
		LEFTBUTTON,
		// 滚轮
		SCROLLBUTTON,
		// 右按钮
		RIGHTBUTTON,
	};

	// 按键
	enum class BoardKey
	{
		KLBUTTON = VK_LBUTTON,
		KRBUTTON = VK_RBUTTON,
		KCANCEL = VK_CANCEL,
		KMBUTTON = VK_MBUTTON,
		
		KKXBUTTON1 = VK_XBUTTON1,
		KKXBUTTON2 = VK_XBUTTON2,
		
		KBACK = VK_BACK,
		KTAB = VK_TAB,
		
		KCLEAR = VK_CLEAR,
		KRETURN = VK_RETURN,
		
		KSHIFT = VK_SHIFT,
		KCONTROL = VK_CONTROL,
		KMENU = VK_MENU,
		KPAUSE = VK_PAUSE,
		KCAPITAL = VK_CAPITAL,
		
		KKANA = VK_KANA,
		KHANGEUL = VK_HANGEUL,
		KHANGUL = VK_HANGUL,
		KJUNJA = VK_JUNJA,
		KFINAL = VK_FINAL,
		KHANJA = VK_HANJA,
		KKANJI = VK_KANJI,
		
		KESCAPE = VK_ESCAPE,
		KCONVERT = VK_CONVERT,
		KNONCONVERT = VK_NONCONVERT,
		KACCEPT = VK_ACCEPT,
		KMODECHANGE = VK_MODECHANGE,

		KSPACE = VK_SPACE,
		KPRIOR = VK_PRIOR,
		KNEXT = VK_NEXT,
		KEND = VK_END,
		KHOME = VK_HOME,
		KLEFT = VK_LEFT,
		KUP = VK_UP,
		KRIGHT = VK_RIGHT,
		KDOWN = VK_DOWN,
		KSELECT = VK_SELECT,
		KPRINT = VK_PRINT,
		KEXECUTE = VK_EXECUTE,
		KSNAPSHOT = VK_SNAPSHOT,
		KINSERT = VK_INSERT,
		KDELETE = VK_DELETE,
		KHELP = VK_HELP,

		K0 = 0X30,
		K1,
		K2,
		K3,
		K4,
		K5,
		K6,
		K7,
		K8,
		K9,

		KA = 0X41,
		KB,
		KC,
		KD,
		KE,
		KF,
		KG,
		KH,
		KI,
		KJ,
		KK,
		KL,
		KM,
		KN,
		KO,
		KP,
		KQ,
		KR,
		KS,
		KT,
		KU,
		KV,
		KW,
		KX,
		KY,
		KZ,

		KLWIN = VK_LWIN,
		KRWIN = VK_RWIN,
		KAPPS = VK_APPS,
		
		KSLEEP = VK_SLEEP,
		
		KNUMPAD0 = VK_NUMPAD0,
		KNUMPAD1 = VK_NUMPAD1,
		KNUMPAD2 = VK_NUMPAD2,
		KNUMPAD3 = VK_NUMPAD3,
		KNUMPAD4 = VK_NUMPAD4,
		KNUMPAD5 = VK_NUMPAD5,
		KNUMPAD6 = VK_NUMPAD6,
		KNUMPAD7 = VK_NUMPAD7,
		KNUMPAD8 = VK_NUMPAD8,
		KNUMPAD9 = VK_NUMPAD9,
		KMULTIPLY = VK_MULTIPLY,
		KADD = VK_ADD,
		KSEPARATOR = VK_SEPARATOR,
		KSUBTRACT = VK_SUBTRACT,
		KDECIMAL = VK_DECIMAL,
		KDIVIDE = VK_DIVIDE,
		KF1 = VK_F1,
		KF2 = VK_F2,
		KF3 = VK_F3,
		KF4 = VK_F4,
		KF5 = VK_F5,
		KF6 = VK_F6,
		KF7 = VK_F7,
		KF8 = VK_F8,
		KF9 = VK_F9,
		KF10 = VK_F10,
		KF11 = VK_F11,
		KF12 = VK_F12,
		KF13 = VK_F13,
		KF14 = VK_F14,
		KF15 = VK_F15,
		KF16 = VK_F16,
		KF17 = VK_F17,
		KF18 = VK_F18,
		KF19 = VK_F19,
		KF20 = VK_F20,
		KF21 = VK_F21,
		KF22 = VK_F22,
		KF23 = VK_F23,
		KF24 = VK_F24,
		
		KNUMLOCK = VK_NUMLOCK,
		KSCROLL = VK_SCROLL,
		
		KOEM_NEC_EQUAL = VK_OEM_NEC_EQUAL,
		
		KOEM_FJ_JISHO = VK_OEM_FJ_JISHO,
		KOEM_FJ_MASSHOU = VK_OEM_FJ_MASSHOU,
		KOEM_FJ_TOUROKU = VK_OEM_FJ_TOUROKU,
		KOEM_FJ_LOYA = VK_OEM_FJ_LOYA,
		KOEM_FJ_ROYA = VK_OEM_FJ_ROYA,
		
		
		KLSHIFT = VK_LSHIFT,
		KRSHIFT = VK_RSHIFT,
		KLCONTROL = VK_LCONTROL,
		KRCONTROL = VK_RCONTROL,
		KLMENU = VK_LMENU,
		KRMENU = VK_RMENU,
		
		
		KBROWSER_BACK = VK_BROWSER_BACK,
		KBROWSER_FORWARD = VK_BROWSER_FORWARD,
		KBROWSER_REFRESH = VK_BROWSER_REFRESH,
		KBROWSER_STOP = VK_BROWSER_STOP,
		KBROWSER_SEARCH = VK_BROWSER_SEARCH,
		KBROWSER_FAVORITES = VK_BROWSER_FAVORITES,
		KBROWSER_HOME = VK_BROWSER_HOME,
		
		KVOLUME_MUTE = VK_VOLUME_MUTE,
		KVOLUME_DOWN = VK_VOLUME_DOWN,
		KVOLUME_UP = VK_VOLUME_UP,
		KMEDIA_NEXT_TRACK = VK_MEDIA_NEXT_TRACK,
		KMEDIA_PREV_TRACK = VK_MEDIA_PREV_TRACK,
		KMEDIA_STOP = VK_MEDIA_STOP,
		KMEDIA_PLAY_PAUSE = VK_MEDIA_PLAY_PAUSE,
		KLAUNCH_MAIL = VK_LAUNCH_MAIL,
		KLAUNCH_MEDIA_SELECT = VK_LAUNCH_MEDIA_SELECT,
		KLAUNCH_APP1 = VK_LAUNCH_APP1,
		KLAUNCH_APP2 = VK_LAUNCH_APP2,
		
		
		KOEM_1 = VK_OEM_1,
		KOEM_PLUS = VK_OEM_PLUS,
		KOEM_COMMA = VK_OEM_COMMA,
		KOEM_MINUS = VK_OEM_MINUS,
		KOEM_PERIOD = VK_OEM_PERIOD,
		KOEM_2 = VK_OEM_2,
		KOEM_3 = VK_OEM_3,
		
		KOEM_4 = VK_OEM_4,
		KOEM_5 = VK_OEM_5,
		KOEM_6 = VK_OEM_6,
		KOEM_7 = VK_OEM_7,
		KOEM_8 = VK_OEM_8,
		
		
		KOEM_AX = VK_OEM_AX,
		KOEM_102 = VK_OEM_102,
		KICO_HELP = VK_ICO_HELP,
		KICO_00 = VK_ICO_00,
		
		KPROCESSKEY = VK_PROCESSKEY,
		
		KICO_CLEAR = VK_ICO_CLEAR,
		
		KPACKET = VK_PACKET,
		
		KOEM_RESET = VK_OEM_RESET,
		KOEM_JUMP = VK_OEM_JUMP,
		KOEM_PA1 = VK_OEM_PA1,
		KOEM_PA2 = VK_OEM_PA2,
		KOEM_PA3 = VK_OEM_PA3,
		KOEM_WSCTRL = VK_OEM_WSCTRL,
		KOEM_CUSEL = VK_OEM_CUSEL,
		KOEM_ATTN = VK_OEM_ATTN,
		KOEM_FINISH = VK_OEM_FINISH,
		KOEM_COPY = VK_OEM_COPY,
		KOEM_AUTO = VK_OEM_AUTO,
		KOEM_ENLW = VK_OEM_ENLW,
		KOEM_BACKTAB = VK_OEM_BACKTAB,
		
		KATTN = VK_ATTN,
		KCRSEL = VK_CRSEL,
		KEXSEL = VK_EXSEL,
		KEREOF = VK_EREOF,
		KPLAY = VK_PLAY,
		KZOOM = VK_ZOOM,
		KNONAME = VK_NONAME,
		KPA1 = VK_PA1,
		KOEM_CLEAR = VK_OEM_CLEAR,
	};
}

